### ISSUE TITLE
LeftMenu disappear blank screen

### ISSUE THREAD

**Issue by nadavdaw** [SocialObjects-Software/AMSlideMenu#103]
Hi, i saw when i am using only left side that when i do a right to left gesture twice fast and straight after a left to right gesture the sidebar disappear, also if you pull half way and use another finger to touch the side bar it also disappear.
Did anyone else see this problem?
and is there a fix?

Thanks

**Comment by ledkof18** [comment]
If you dont use right menu, disable to prevent this issue

in viewdidload add:

self.mainSlideMenu.slideMenuDelegate = self;
[self disableSlidePanGestureForRightMenu];

and the problem will be fixed.

**Comment by at90vader** [comment]
that didn't solved the problem. :(
