### ISSUE TITLE
Present UIViewController on AMSlideMenuRightMenuViewController 

### ISSUE THREAD

**Issue by woudwijk84** [SocialObjects-Software/AMSlideMenu#108]
First thanks for this amazing library! Also i have one question. Is it possible to present a viewcontroller above the right menu like in the pictures below, that when selecting a tableviewcell it opens the contentsegue as a pushsegue without filling the screen. Hope you can help. Thanks in advance. 
![foto 1](https://cloud.githubusercontent.com/assets/5072998/4117056/7b248a72-328c-11e4-95d8-3c402ada3c0c.PNG)
![foto 2](https://cloud.githubusercontent.com/assets/5072998/4117057/7e515b76-328c-11e4-8e02-48b9c9957fa7.PNG)

**Comment by arturdev** [comment]
Unfortunately, AMSlideMenu doesn't support functionality like that.
