### ISSUE TITLE
Content view controller missing bottom part in 3.5 inch iPhone

### ISSUE THREAD

**Issue by Draftdog** [SocialObjects-Software/AMSlideMenu#113]
I'm using version 1.5.3, all is fine using a 4" iPhone, but on the 3.5" iPhone I'm getting a weird behavior: the bottom 100px or so is missing from the content view controller, the menu is always correctly sized.

![bad-vc](https://cloud.githubusercontent.com/assets/8707823/4199870/f455adea-3809-11e4-9ba2-704d2d3dec55.png)

One way to fix it is to change AMSlideMenuMainViewController and do this at line 661:
    [self.view addSubview:nvc.view];
    CGRect frame = nvc.view.frame;
    frame.origin.y = 0;
    frame.size.height = self.view.bounds.size.height;
    nvc.view.frame = frame;
    [self configureDarknessView];

![good-vc](https://cloud.githubusercontent.com/assets/8707823/4199874/fa060dca-3809-11e4-89c7-eb5bde2a30ba.png)
 
I haven't tested this with storyboards. 
Thanks for a very useful component!

**Comment by arturdev** [comment]
Your mistake is the existence of MainVC.xib. 
MainVC must be blank view controller without any views on it. 
You shouldn't use it for displaying any views. Use content view controllers instead. 

P.S.
Sorry for such a late reply.
