### ISSUE TITLE
IOS 8 Support?  disableSlidePanGestureForLeftMenu 

### ISSUE THREAD

**Issue by sirhcmcd** [SocialObjects-Software/AMSlideMenu#115]
I have a Login page that uses disableSlidePanGestureForLeftMenu that I believe doesn't work anymore after upgrading to IOS 8.  Have you confirmed any issues with IOS 8 yet?  Trying to troubleshoot this before making any more changes.

**Comment by sohanvanani** [comment]
it also didn't worked for me. 
please fix this issue.

**Comment by arturdev** [comment]
It works on iOS 8. You must call  `disableSlidePanGestureForLeftMenu` method in `-viewWillAppear:` method. 
Please see the demo project

**Comment by gatewayboys** [comment]
I have never had a problem with this, but now is anyone getting this issue in iOS 9. I do call disableSlidePanGestureForLeftMenu in ViewWillAppear

**Comment by simonbromberg** [comment]
It does not seem to work consistently. Removing the lines that re-enable the pan in my_viewWillDisappear seems to work. Side note, sometimes that method gets called multiple times even though there's only one view disappearing.

**Comment by mxnmike** [comment]
is there a workaround this my_viewwilldissapear??? its messing up with my settings, i have a setup where it shouln't show, and my_viewwilldissapear is called multiple times, and viewwillappear doesnt.
