### ISSUE TITLE
You cannot change RightSlideMenu color from storyboard in latest xcode 6.1 for iPad

### ISSUE THREAD

**Issue by ketansakariya** [SocialObjects-Software/AMSlideMenu#124]
You cannot change RightSlideMenu color from xib in latest xcode 6.1 for iPad.
I am not sure. This might be xcode or other issue than the library. As color changing in storyboard works fine for iPhone.

**Comment by arturdev** [comment]
You're right. 
Xcode - country of bugs and wonders
