### ISSUE TITLE
Graphical bug when the menu is closing

### ISSUE THREAD

**Issue by Aceking95** [SocialObjects-Software/AMSlideMenu#129]
When i select a row in the menu, often i get "black" tableview while menu is closing. 
Here is a video ( when i click Diary it happens ).
https://www.youtube.com/watch?v=5mekUx-Ej9c
Here is a screen:
http://mauriziofaleo.altervista.org/bug.png

I've also tried on devices ( Iphone 6, 6 plus and 5 ) with same results.

What is the problem?

**Comment by arturdev** [comment]
check this #18
