### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by alexissan** [SocialObjects-Software/AMSlideMenu#130]
What do you think about adding a configuration file (a json file, for example) to make it easier to set default settings?

Following 'The pragmatic programmer' book:

__Rule 6: Configure, don’t integrate__

Details mess up our pristine code, they change frequently. Every change to the code is a risk to break the system. To avoid that, you should get the details out of the code, in configuration files. Configurable code is called « soft code », it’s adaptable to change.

Whenever you come to the point where you put details into your codebase, stop, and extract them out of it. The time you spend now will pay-off ten times in the future.

**Comment by arturdev** [comment]
The reason that I made it this way is that its dynamic,  you can change default values at runtime. 
You can set multiple conditions and return different values (menu width, effects, menu content, etc...)
