### ISSUE TITLE
Menu not deallocating when changing root view controller

### ISSUE THREAD

**Issue by m4rcoperuano** [SocialObjects-Software/AMSlideMenu#133]
First, awesome tool man! Love the great work you've put into this. 

Now to my issue. In my app delegate, I switch the root view controller from my login page to my actual app, which uses AMSlideMenu. Everything is working great, except when I log out and log back in. When i do this, I switch the root view controller back to the login, and then back to the app. During my testing, I saw that the main dashboard view of the app never gets deallocated. I confirmed that it wasn't my code that was doing it (tested using an empty VC). So I suspect that AMSlideMenu could be causing it somewhere. It looks like the "allInstances" variable keeps getting more and more instances the more I log out and log back in - it's also giving me a "nil" value whenever I make a call to the "[self mainMenu]" method. Just thought I'd report this here. 

Thank you for your time :)

**Comment by m4rcoperuano** [comment]
BTW - iOS 8.1 app in objective C

**Comment by arturdev** [comment]
already fixed :)

**Comment by simonbromberg** [comment]
What was the fix?
