### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by FlexAble73** [SocialObjects-Software/AMSlideMenu#134]
Every time you select a viewController from the menu you get always a new instance of viewcontroller... so every time viewDidLoad run ... it's a problem if you have to load data only one time per viewcontrollers or set an observer in a viewdidload.Can u help me ?

**Comment by arturdev** [comment]
You can create a Singleton objects for loading you data only one time. 
Or you can use `dispatch_once` by passing token that declared as  static.
```ObjC
//...
 static dispatch_once_t onceToken;
@implementation
- (void)foo
{
    dispatch_once(&onceToken, ^{
           //Do your stuff 
    });
}
```

For setting observers you can use `-viewWillAppear:` and `-viewWillDisappear:` methods, e.g.
```ObjC
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
   //... 
  
   //here add your observers
}

- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
   //...
  
   //here remove all observers  
}
```
