### ISSUE TITLE
How to cancel the panGesture when have pushed into a viewcontroller? 

### ISSUE THREAD

**Issue by seanLee** [SocialObjects-Software/AMSlideMenu#135]
I use ````[self.navigationController pushViewController:view animated:YES]```` to push a new ViewController.But it can accept the panGesture of the slideMenu.

when I use ````UINavigationController *navi = [[UINavigationController alloc] initWithRootViewController:advc];
    [self presentViewController:navi animated:YES completion:nil];````It can't be paned to slidemenu.

My question is how can I cancel the panGesture if I want use ````[self.navigationController pushViewController:view animated:YES]````

**Comment by arturdev** [comment]
You must import `UIViewController+AMSlideMenu.h` category and use following methods in `viewWillAppear:` method
```Obj-C
- (void)disableSlidePanGestureForLeftMenu;
- (void)disableSlidePanGestureForRightMenu;
- (void)enableSlidePanGestureForLeftMenu;
- (void)enableSlidePanGestureForRightMenu;
```

**Comment by seanLee** [comment]
@arturdev  lately I found this way.But it doesn't work for me. I'm working with IOS8 and I find an other iusse said that it doesn't work either.

**Comment by arturdev** [comment]
Ok, I'll fix that for iOS8 asap

**Comment by seanLee** [comment]
thx very much

**Comment by nassifbasheer** [comment]
Can you the below code 

    AMSlideMenuMainViewController *mainVC = [AMSlideMenuMainViewController getInstanceForVC:self];
    mainVC.leftPanDisabled = TRUE;
    mainVC.rightPanDisabled = TRUE;

**Comment by gatewayboys** [comment]
Could you look into an issue that I am having, I can disable the pan gesture for a pushed VC, however  I have that VC push to another VC.  On the second VC I cannot disable the pan gesture no matter what I try.  The result is an unwanted pan gesture that pushes my view back to the first VC!

I am so mind boggled by this issue. I really love this API, but this last issue is causing havoc. Thanks for you help.

**Comment by arturdev** [comment]
Import "UIViewController+AMSlideMenu.h"
And in - viewWillAppear: method do
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    self.mainSlideMenu.leftPanDisabled = YES;
    self.mainSlideMenu.rightPanDisabled = YES;
}

**Comment by arturdev** [comment]
but this only disable pan for menu, e.g. you can't open the menu via swipe,
only via menu button.

**Comment by gatewayboys** [comment]
see what happens is that when in the second view the pan triggers a slide over that pushes me back to the first view, it's triggered by an edge of screen ui gesture still can't disable it, again it works for the first view stopping the menu from appearing on the gesture, but still have the problem in the second view controller

**Comment by gatewayboys** [comment]
So my apologies, the pan gesture was Apple's self.navigationController.interactivePopGestureRecognizer.enabled = NO;

I just thought it was the AMSlideMenu inside my second pushed VC.  Thx for your help, love this software.

**Comment by simonbromberg** [comment]
This still doesn't work; Works for first view in navigation stack, but after a push the pan gesture is enabled again.

**Comment by gatewayboys** [comment]
I had that problem, but solved it with this...if you haven't already tried it.

self.navigationController.interactivePopGestureRecognizer.enabled = NO;

**Comment by hardikamal** [comment]
Still not working...facing in the issue in nextview controller...do i have to write this code in every view controller of the navigation stack??

**Comment by arturdev** [comment]
@hardikamal  Yes! You must write that code in every view controller (in `-viewWillAppear:` method) of that navigation stack.

**Comment by hardikamal** [comment]
@arturdev Its working at first and if you open and close alert or actionsheet the left pan start opening again on slide...ie viewwillappear method does not get called on alert popup close...i tried with viewdidappear but its same as view did appear....

**Comment by arturdev** [comment]
@hardikamal Can you manually call that method again after closing actionsheet/alert ?

**Comment by hardikamal** [comment]
@arturdev ohhk cool

**Comment by hardikamal** [comment]
@arturdev is this fixed??
