### ISSUE TITLE
Can i Make Navigation Bar Static?

### ISSUE THREAD

**Issue by Vishaliphone** [SocialObjects-Software/AMSlideMenu#136]
Hallo,
In one of my project there is Requirement where I want to give Side menu effect as attached in below image.

Here navigation bar will be Non - Movable and slide view controller slide below the Navigation bar.
Is that possible with this library?
Please help me regarding this.

![screen shot 2015-02-11 at 5 22 21 pm](https://cloud.githubusercontent.com/assets/6514316/6146458/e03796d8-b212-11e4-96a7-3850bf1d5625.png)

**Comment by arturdev** [comment]
No, AMSlideMenu hasn't that functionality.

**Comment by Vishaliphone** [comment]
Hi arturdev,
Can you provide any reference for achieve it?
It will be great help for me and also for others whom are looking for it.

Thanks & Regards,
 Vishal sharma.

**Comment by arturdev** [comment]
If your navigation controller isn't semitransparent, than you can get the navigationbar's view and add it as subview directly to window and bring it to front. This whey if you open the menu, it will behind navigation bar.
This is dirty and quick solution and not good practice. 

I strongly recommend you to find another library that does this with right way

**Comment by arturdev** [comment]
and check this one: https://github.com/calvinchankf/CCKFNavDrawer
just found it
