### ISSUE TITLE
Presenting Modally From Detached ViewController

### ISSUE THREAD

**Issue by ddeger** [SocialObjects-Software/AMSlideMenu#137]
Hi,

I'm trying to present a VC modally from the VC of one of the selected slide menu items. However, I keep receiving this warning:

Presenting view controllers on detached view controllers is discouraged.

Can someone, please, help me?

**Comment by jkoepcke** [comment]
I can see the same problem. It's especially bad if you try to show a modal screen with another navigation in it, then you get unpredictable states.

**Comment by arturdev** [comment]
If you use the version from cocoapods then please make sure that this line https://github.com/NinoScript/AMSlideMenu/commit/5df647e1a4e0bcd2b7d3fef8b87427f8c61f1042
exists  there. If not then just add it

**Comment by jkoepcke** [comment]
That fixes it! You should absolutely create a pull request for this one. Thanks a lot!

**Comment by jlindenbaum** [comment]
Would be great if we can add this into a bug fix release, instead of closing this ticket.
