### ISSUE TITLE
my_dealloc call when keyboard hide in UIWebView

### ISSUE THREAD

**Issue by zixsma** [SocialObjects-Software/AMSlideMenu#138]
This problem cause disable pan gesture stop working after keyboard in UIWebView show up. my_dealloc  is called after keyboard hide.
This UIViewController contain UIView > UIWebView and I push to this UIViewController from UIViewController which connect to RightMenuViewController by AMSlideMenuContentSegue

**Comment by arturdev** [comment]
fixed
