### ISSUE TITLE
How to show mainVC by default?

### ISSUE THREAD

**Issue by anotheryang** [SocialObjects-Software/AMSlideMenu#139]
I added one label in MainVC, and wanted to show MainVC when the app is open instead of show Left ViewController OR Right ViewController. How can I archive it? Thanks.

**Comment by sohanvanani** [comment]
I am also facing this. I want to show my mainvc not from leftmenu. I am using it in ios 8.2 swift using objective c bridging header without storyboard. I have assign AMSlideMenuMainViewController to my mainvc. but It loads view from my leftmenu. how to load mainvc as startup??  my mainvc contain one button and I want to open left menu when button pressed. or when user slide right side. but only on mainvc. not in my all project. I have tried this disableSlidePanGestureForLeftMenu() but it didn't worked for me please get me out of this problems please help me.

**Comment by arturdev** [comment]
You shouldn't use MainVC at all! Just use initial view controller.
https://github.com/SocialObjects-Software/AMSlideMenu/blob/master/AMSlideMenu/AMSlideMenuMainViewController.h#L157

**Comment by BigWillieStyle** [comment]
@arturdev Can you explain?  I'm facing the same problem.  I'm learning Objective-C and have worked through your sample and it works great.  But I'm working on an app with a main screen and a menu button in the top left.  So how can I call/activated the AMSlideMainViewController when the IBAction occurs. If there's a better way I'm open!!!

**Comment by BigWillieStyle** [comment]
@arturdev One suggestion:  Looking through the code and comparing with other controls, it would be nice not ti set the AMPrimaryMenuLeft and overlay the ViewController with the left menu by default.  This would allow users to extend the AMSlideMainViewController as the standard ViewController.  This would offer more flexibility.
