### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by orlanczyk** [SocialObjects-Software/AMSlideMenu#140]
i have a huge bug. i have built an app using this library works fine on iPhone 5 and 6 but crashes on iPhones 5s and 4s! and the weird thing is the error is:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Receiver (<MainVC: 0x7c199fe0>) has no segue with identifier 'rightMenu''

i have tried a whole day to find a solution with no luck!

**Comment by arturdev** [comment]
I can't help you without any source codes.

**Comment by orlanczyk** [comment]
I have been working all night and found the problem! for some weird reason you can't make network data requests inside viewDidLoad of the side menu controller. i was calling a method for bringing profile image from parse and only when i disabled it from the viewDidLoad the problem was solved.
thanks for the response anyway!
