### ISSUE TITLE
tableview swipe to delete doesn't work!

### ISSUE THREAD

**Issue by ddeger** [SocialObjects-Software/AMSlideMenu#142]
Hi,

I'm disabling the right pan gesture in my rootVC of a navigation controller, but my swipe to delete of tableview doesn't work. Actually, it works sometimes, but very rare. How do you think I can fix this?

Thanks,
Deger

**Comment by arturdev** [comment]
Are you sure that you have the latest version?

**Comment by arturdev** [comment]
I tested with demo project and everything works fine. 
Please pull the latest version and check it yourself. I added ediable tableview in "Demo Slider with Both menus" example
