### ISSUE TITLE
Background image for selected index

### ISSUE THREAD

**Issue by midhunsivaraj** [SocialObjects-Software/AMSlideMenu#145]
Is it possible to add an image or colour as background when we select an index item from slide menu?

**Comment by arturdev** [comment]
Can you describe more detail? Or will be better if you provide a screenshot.

**Comment by midhunsivaraj** [comment]
![screen shot 2015-04-06 at 8 00 07 pm](https://cloud.githubusercontent.com/assets/1523266/7005646/ae5e34b4-dc97-11e4-8e11-c86dff40f03a.png)

I want to change the colour of the selected item. The selected item in screenshot is Messages. Thank you very much for your help in advance.

**Comment by arturdev** [comment]
Just make a subclass from AMSlideMenuLeftTableViewController and set that class to your left menu form storyboard, and change selected color as you do that usually.
