### ISSUE TITLE
LeftMenu doesnot fit to the explicit width 

### ISSUE THREAD

**Issue by nassifbasheer** [SocialObjects-Software/AMSlideMenu#146]
Hi ,

I am a new bee to swift and i have integrated AMSlideMenu to the project. I have used this library for a couple of Obj projects. Ok right now what am trying to find out is adjust the width of the left menu. I have overridden the width on a Mainviewcontroller.swift which is a subclass of AMSlideMenuMainViewController. The left menu is not framed to the width i have asked for. When i slide or open the left menu ,it looks like left menu screen is taking the full screen . I have only left menu in this project no right menu

import UIKit

class MainMenuViewController: AMSlideMenuMainViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    override func segueIdentifierForIndexPathInLeftMenu(indexPath: NSIndexPath!) -> String! {
        switch (indexPath.row) {
       
        case 0 :
            return "showHomeScreen1"
            
        case 1 :
            
            return "showHomeScreen2"

            
        default :
            
            return "showHomeScreen1"
        }
    }
    
    override func initialIndexPathForLeftMenu() -> NSIndexPath! {
        return NSIndexPath(forRow: 0, inSection: 0);
    }
    
     override func leftMenuWidth() -> CGFloat {
        return 160
    }

}

**Comment by arturdev** [comment]
I haven't learned swift language yet, so I can't help you here, sorry.
You can ask those king of questions in http://stackoverflow.com
