### ISSUE TITLE
Warnings since Xcode 6.4

### ISSUE THREAD

**Issue by Chrischi81** [SocialObjects-Software/AMSlideMenu#148]
Hello,

i used your AMSLideMenu before Xcode 6.4 was relaesed, without any warning.
Since Xcode 6.4 i become multiple warnings. Can i fix them self or must i wait for an update with "pod update"?

Warning in:  if (abs(translation.x) > kPanMinTranslationX && translation.x < 0)
                {
                    [self openRightMenu];
                }
Fix:  if (fabs(translation.x) > kPanMinTranslationX && translation.x < 0)
                {
                    [self openRightMenu];
                }
is that correct?

![bildschirmfoto 2015-04-21 um 10 39 45](https://cloud.githubusercontent.com/assets/8289700/7248432/e7b48c32-e812-11e4-80ef-874c242aa4e3.png)

**Comment by arturdev** [comment]
Yes, you can fix them yourself
