### ISSUE TITLE
LeftMenu not visible with orientation changes in iPad

### ISSUE THREAD

**Issue by nassifbasheer** [SocialObjects-Software/AMSlideMenu#149]
I have integrated the AMSlideMenu with pods in my project. Launching the app with any mode, i slided the screen to open the left menu , closed the menu and did the orientation change. On opening the left menu , i donot see the left menu , the left frame is shifted to the container views "x" position.

If i rotate the device with the left menu opened , this issue doesnot appear

**Comment by arturdev** [comment]
Can you check the demo project please? Because for me its working with the demo project.
Thanks.

**Comment by nassifbasheer** [comment]
This is my fifth project with AMSlideMenu (1st with iPad) , and i haven't faced this weird issue. Need to checkout if i am doing anything wrong.

Thanks for the reply

**Comment by nassifbasheer** [comment]
I donot know what was going wrong in my case . I overrided the openLeftMenu and adjusted the frame for the left menu and this is working now

**Comment by arturdev** [comment]
Then, I'll close this issue

**Comment by nassifbasheer** [comment]
Sure, thanks
