### ISSUE TITLE
Can we use UIViewController for left menu instead of UITableViewController in this AMSlideMenu version? 

### ISSUE THREAD

**Issue by daljeet16** [SocialObjects-Software/AMSlideMenu#150]
I am using this library in my app for side menu and is working fine as such, but but I have a specific requirement which I am unable to achieve with the current version. 

When I add a view in UITableViewController, then the complete view is scrolling which I don't want.That is why I tried to add UIViewController containing a tableview which has a view as a subview of UIViewController.  But in this case, AMSlideMenu stops working.

This functionality is absolutely similar to the attached screenshot from google maps app, which has the top part as static and the list is scrollable.
 
![img_3001](https://cloud.githubusercontent.com/assets/9800506/7534275/b564974a-f596-11e4-963d-b430f7c4c11a.png)

Is there any solution to meet this design requirement ? ( in a new release probably ) 
Help is appreciated, thanks!

**Comment by arturdev** [comment]
Unfortunately you can't use UIViewController as menu in this version of AMSlideMenu.
But you can achieve that with UITableViewController too. 
E.g. you can set tableview style to group, and use section header's view.

**Comment by arturdev** [comment]
Or, If  you look at this: <a href="https://github.com/SocialObjects-Software/AMSlideMenu/blob/master/AMSlideMenuDemo-with%20Storyboard/AMSlideMenu/LeftMenuVC.m">link</a>, you can see a little hack (in `-setFixedStatusBar` method) that I made in UITableViewController. This partly makes UITableViewController like UIViewController. 
Just replace  `statusBarView ` with your static header view :)

**Comment by daljeet16** [comment]
Hi Artur

I have implemented as same as you suggested with viewForHeaderInSection and its working fine.
Thanks a lot for the same.

I'm facing another issue now while implementing this, I hope you can help in the same. 

I'm using AMSlideMenu with storyboards and implemented with tab bar viewController, but now the slider button is not appearing in the navigation bar.
This is the code in MainVC.m :-  
- (void)configureLeftMenuButton:(UIButton *)button
{
    CGRect frame = button.frame;
    frame.origin = (CGPoint){0,0};
    frame.size = (CGSize){40,40};
      button.frame = frame;
    [button setImage:[UIImage imageNamed:@"simpleMenuButton"] forState:UIControlStateNormal];
}

I have tried putting breakpoint in the above code and the code executes, but the button does not appear. Look forward to your help. 

Thanks so much !

**Comment by arturdev** [comment]
Can you make a demo project and send it to me via email (mkrtarturdev@gmail.com) ?
I can't say anything without looking what have you done :)

**Comment by hardikamal** [comment]
@daljeet16  even i want to setup this type of layout on left menu.... how did u solve can u plz share the code of it??

**Comment by daljeet16** [comment]
@hardikamal here is the code.

- (UIView *) tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
{
    
    UIImageView *userImage=[[UIImageView alloc] initWithFrame:CGRectMake(15, 30, 80, 80)];
    
    UIView *sectionHeader = [[UIView alloc] init];
    sectionHeader.backgroundColor = [UIColor colorWithRed:85.0/255.0 green:139.0/255.0 blue:47.0/255.0 alpha:1.0];
    [sectionHeader addSubview:userName];
    return sectionHeader;
}

-(CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section{
    return 170.0f;
}

**Comment by hardikamal** [comment]
@daljeet16  where do i place this code....and what is this variable userName that is giving some error plz help

**Comment by daljeet16** [comment]
You have to put in AMSlideMenuLeftTableViewController class i updated the comment it is userImage not userName.

**Comment by daljeet16** [comment]
Hi Artur

@arturdev I created a sample project with storyboard and tabBar, in that everything is working fine the button appear in navBar but when I did the same thing in my app project the slider button is not coming.

I can't share my whole project with you is there any other way to solve this issue.

**Comment by hardikamal** [comment]
@daljeet16 Solved thanks bro

**Comment by arturdev** [comment]
Actually it isn't good practice to make changes in the Library. 
I strongly recommend you to make a subclass from `AMSlideMenuLeftTableViewController` and do your customizations there.

**Comment by hardikamal** [comment]
@arturdev yeah did that only...Thanks for the suggestion and awesome library

**Comment by daljeet16** [comment]
@arturdev  This is my storyboard structure,hope it give some clarity to you

![screen shot 2015-05-14 at 5 47 52 pm](https://cloud.githubusercontent.com/assets/9800506/7631619/2f34e604-fa62-11e4-93d3-cdc59a256b86.png)

**Comment by arturdev** [comment]
Hmm. Try `[self addLeftMenuButton]` in that view controller. And don't forget to import "UIViewController+AMSlideMenu.h"

**Comment by arturdev** [comment]
@hardikamal  You're welcome! :)

**Comment by daljeet16** [comment]
@arturdev  its working thanks!

**Comment by arturdev** [comment]
@daljeet16 You're welcome!
