### ISSUE TITLE
Use UIScreenEdgePanGestureRecognizer 

### ISSUE THREAD

**Issue by dimohamdy** [SocialObjects-Software/AMSlideMenu#151]
I can't drag menu if the main ViewController is MKMapview ,please add feature of use UIScreenEdgePanGestureRecognizer for dragging and how i can solve this problem ?

**Comment by arturdev** [comment]
There is a very simple solution. 
<a href="http://stackoverflow.com/questions/24833467/use-uiscreenedgepangesturerecognizer-without-moving-mkmapview/24989917#24989917">Click me :)</a>

**Comment by dimohamdy** [comment]
Thanks I Make it

**Comment by dimohamdy** [comment]
can i use AMSlideMenu in MapView without change library

**Comment by arturdev** [comment]
what you mean?

**Comment by dimohamdy** [comment]
i add map view as content View but the swipe in pan gesture in map not work?

**Comment by arturdev** [comment]
Have you checked the solution that I already posted?

**Comment by dimohamdy** [comment]
yes, i used UIScreenEdgePanGestureRecognizer but i can't close it by dragging.

**Comment by arturdev** [comment]
Please, read this answer : http://stackoverflow.com/questions/24833467/use-uiscreenedgepangesturerecognizer-without-moving-mkmapview/24989917#24989917

**Comment by dimohamdy** [comment]
when using UIScreenEdgePanGestureRecognizer
if i open the left menu i can't close it menu by dragging?
