### ISSUE TITLE
UISearchController's searchbar doesn't move with current view

### ISSUE THREAD

**Issue by trungnguyen1791** [SocialObjects-Software/AMSlideMenu#153]
![img_0667](https://cloud.githubusercontent.com/assets/3167319/7940596/1c92ed38-097c-11e5-9f23-480a533b6ae9.JPG)

Anyone have same problem? I'm using UISearchController inside my app. When the searchbar is selected, i swipe (or tap on expand button ) and it happened.

**Comment by trungnguyen1791** [comment]
@arturdev . What about this bugs, can u help me to solve this?

**Comment by arturdev** [comment]
can you send me a demo project?

**Comment by trungnguyen1791** [comment]
After debug, i think we have problem with this new type UISearchController. When i active searchbar, (maybe) this search controller show a modal view  on top of your overlay view.
You can see image below.
![screen shot 2015-06-29 at 3 36 42 am](https://cloud.githubusercontent.com/assets/3167319/8398209/18c006d4-1e10-11e5-8217-16f8b5dab0ad.png)

Project's workflow is simple like that:
- A view controller with tableView.
- A UISearchcontroller ( new component in iOS 8)
- Add searchcontroller.searchBar as tableview header view.
- Try active search bar ( to search something...etc).
- Select a result to push to new view controller ( or press left menu button to show Left Menu View)
Then the problem will show. That searchbar UI doesn't move with main view.

**Comment by trungnguyen1791** [comment]
Good new. That problem is resolved.
May be this link will help who have same problems with me .
http://stackoverflow.com/questions/29610873/uisearchcontroller-not-dismissed-when-view-is-pushed
