### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by dnamna** [SocialObjects-Software/AMSlideMenu#157]
Hello,
I have installed the pod,inherited a viewcontroller from AMSlideMenuMainViewController and created a table view which inherits AMSlideMenuRightTableViewController.
viewcontroller viewdidload:

```Obj-C
 UIStoryboard *mainStoryboard = [UIStoryboard storyboardWithName:@"Main"
                                                             bundle: nil];
 MenuTableViewController *controller = [mainStoryboard instantiateViewControllerWithIdentifier:@"MenuTableView"];
 self.rightMenu = controller;
```

When I launch my application configureRightMenuButton is not triggered.
Any ideas? am I missing something,I didn't add the mainvc but I added the methods of mainvc to my viewcontroller and I didn't add anything to the appdelegate. I already have my navigationcontroller in my app in the storyboard,but I need to implement your lib in my application.
Thx

**Comment by arturdev** [comment]
As I understand You want to use the lib without storyboards. In that case, all points of this <a href="https://github.com/SocialObjects-Software/AMSlideMenu#usage-with-storyboards">guide</a> are mandatory. 
Or you can just watch this <a href="https://www.youtube.com/watch?v=y33t_bWS_Zk">video tutorial <a/>.

**Comment by dnamna** [comment]
I was able to add the right menu but sadly the rightmenu button is not displayed in the navigationbar.
And the right table view is opened by default behind my viewcontroller on load.
I debugged and not exceptions or errors

**Comment by arturdev** [comment]
Please, just follow to the video tutorial from my previous comment.

**Comment by Sasikumariosdeveloper** [comment]
can u send the image picker third party working class file..urgent
