### ISSUE TITLE
how to make opening and closing the menu faster

### ISSUE THREAD

**Issue by rashidasgari** [SocialObjects-Software/AMSlideMenu#158]
Is there anyway to make opening and closing the menu a bit faster? I could't find anything in the tutorial.

**Comment by arturdev** [comment]
Yes of-course. 
Just override those methods in your MainVC class

https://github.com/SocialObjects-Software/AMSlideMenu/blob/master/AMSlideMenu/AMSlideMenuMainViewController.h#L121-L131
