### ISSUE TITLE
subclassing AMSlideMenuRightTableViewController (question)

### ISSUE THREAD

**Issue by chrisDwarner** [SocialObjects-Software/AMSlideMenu#160]
Is it is possible to subclass one of the side menu table view controllers?  I need to dynamically update the contents of the menu.  I currently have the side menu implemented in a storyboard, and now I need to update the menu items to reflect the current state of the application at runtime.

**Comment by arturdev** [comment]
Yes of course you can. Just make a subclass of `AMSlideMenuLeftTableViewController` or `AMSlideMenuRightTableViewController`, customise as your wish, and set that class from storyboard to your menu table view controller.

**Comment by chrisDwarner** [comment]
awesome thank you for the quick reply!
