### ISSUE TITLE
'NSInvalidArgumentException', reason: 'Receiver (<MainVC: 0x7fd181ca9110>) has no segue with identifier 'rightMenu''

### ISSUE THREAD

**Issue by ihmunro** [SocialObjects-Software/AMSlideMenu#162]
Hi There

I copied all the non storyboard files and updated my app etc, but when I run the App, it crashes with the following error:

'NSInvalidArgumentException', reason: 'Receiver (<MainVC: 0x7fd181ca9110>) has no segue with identifier 'rightMenu''

Any ideas ?

I did look at the other issue similar to this, but nothing seems to fix it.

Iain

**Comment by maxprig** [comment]
I have the same problem :c

**Comment by arturdev** [comment]
Probably you did something wrong. 
Please, follow this tuto: https://www.youtube.com/watch?v=y33t_bWS_Zk

**Comment by arturdev** [comment]
And make sure that you have set class to your left/right menu's table view controller form storyboard.
btw, it must be inherited from AMSlideMenuLeftTableViewController
