### ISSUE TITLE
leftMenuDidOpen not work

### ISSUE THREAD

**Issue by gaf09** [SocialObjects-Software/AMSlideMenu#164]
Hi,

I'm trying to implement the library. Everything works fine but not working the callback  `leftMenuWillOpen `. I implemented the Deletages, and everything like this in the documentation but not working. However, other features such as the width of the menu do work perfectly.

Attached my sample code.

Regards,

FIle: `ViewController.h`

```
#import "AMSlideMenuMainViewController.h"
#import "AMSlideMenuProtocols.h"

@interface ViewController : AMSlideMenuMainViewController<AMSlideMenuDelegate>

@end
```

FIle: `ViewController.m`

```
#import "ViewController.h"
#import "UIViewController+AMSlideMenu.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
}

- (CGFloat)leftMenuWidth { // works fine
    return [UIScreen mainScreen].applicationFrame.size.width;
}

- (void)leftMenuWillOpen { // NO WORK!!
    // Close keyboard
    [self.view endEditing:YES];
    
    NSLog(@"MENU ABIERTO");
}

- (BOOL)deepnessForLeftMenu { // works fine
    return YES;
}

- (void)configureLeftMenuButton:(UIButton *)button { // works fine
    ...
}

....

}
```

**Comment by arturdev** [comment]
Hi. 
As I described in the ReadMe: 
"If you want to get menu's open/close callbacks, then <b>set MainVC's delegate property</b>, and implement protocol named 'AMSlideMenuDelegate' which declared in 'AMSlideMenuProtocols.h'."

This means: 

```Obj-C
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
   
    self.slideMenuDelegate = self;
}
```

**Comment by gaf09** [comment]
Oops, sorry for the distraction. Now it works great!!

Regards,
