### ISSUE TITLE
Back button not showing in a iOS 9 build

### ISSUE THREAD

**Issue by tharpa** [SocialObjects-Software/AMSlideMenu#165]
I have a problem with the pushed view controller which in iOS 9 doesn't show any back button. Running in the the iOS 8.4 simulator shows the back button correctly.  Any hints how to resolve that?

**Comment by arturdev** [comment]
Please run the demo project and make sure that this bug exists there too. 
Right now I'm running the project on iPhone6S (iOS9.0) and everything is OK. 
![simulator screen shot oct 29 2015 11 36 02 am](https://cloud.githubusercontent.com/assets/6263856/10812601/ea2cb71c-7e28-11e5-9e46-8102cf33538e.png)

**Comment by tharpa** [comment]
You still run in iOS 6 compatibility mode (you see that because your views are letterboxed) because you missing assets for iOS 7 and later in the demo project.  Nevertheless, converting the project to use image asset and adding launch screens for newer devices, your demo code works fine.

![simulator screen shot 03 nov 2015 13 25 34](https://cloud.githubusercontent.com/assets/1071496/10907989/9ab9433a-822e-11e5-83bc-65ee0c64d93c.png)

Do you have any idea what to look for in my app to resolve the issue?

**Comment by arturdev** [comment]
Actually I can't say anything until I see your project.

**Comment by tharpa** [comment]
-> Artur Mkrtchyan writes:

> Actually I can't say anything until I see your project.

Hi Artur, 

That's sounds nice.  Would you be willing to have a look?  I could give
you access to the Bitbucket git repo of the project; I don't have
private repos on Github.  Would it work for you?  Alternatively, I could
put the git repo on my server.  Let me know, what works best for you.

cheers
-- 
-rafał

**Comment by arturdev** [comment]
Ok. Give me access to the bitbucket's repo.

**Comment by tharpa** [comment]
-> Artur Mkrtchyan writes:

> Ok. Give me access to the bitbucket's repo. 

What's your email address or user name there?
-- 
-rafał

**Comment by arturdev** [comment]
email: mkrtarturdev@gmail.com
