### ISSUE TITLE
How can I change ViewController without changing NavigationBar?

### ISSUE THREAD

**Issue by ftp27** [SocialObjects-Software/AMSlideMenu#166]
My application has side menu with a button that opens the form.   After submitting this form I want to show the other ViewController with results of this submitting. How can I change this ViewController Form to ViewController with result without changing NavigationBar with button for opening side menu?

**Comment by arturdev** [comment]
Just push to that ViewController and in the implementation file to the following:
```ObjC
#import "UIViewController+AMSlideMenu.h"
//...
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWIllAppear:animated]

   [self.mainSlideMenu addLeftMenuButton];
}
```

**Comment by ftp27** [comment]
This is don't work for me. May be it don't work because as presented ViewController I use UITableViewController..

**Comment by arturdev** [comment]
Как именно ты показываешь новый ViewController? 
Покажи код , который работает после нажатия кнопки отправки формы.

**Comment by ftp27** [comment]
О. Шикарно. Так попроще )

Вот тут цепляется загружаемый ответ и показывается

```
Stream *stream = [mappingResult firstObject];
[Notifications hideProgress:self.view];
ThreadViewController *vc = [self.storyboard instantiateViewControllerWithIdentifier:@"streamScreen"];
[vc setStream:stream];
UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:vc];
[self.mainSlideMenu addLeftMenuButton];
[self presentViewController:vc animated:YES completion:nil];
```

Внутри ThreadViewController я добавил тот код с viewWillAppear

**Comment by arturdev** [comment]
О почему открываешь ThreadViewController модально, а не так:
```ObjC
[self.navigationController pushViewController:vc animated:YES];
```

**Comment by ftp27** [comment]
Вероятно, потому что я пишу 3 недели только для iOS и еще нубоват. Так или иначе такой вариант не работает. Так как self.navigationController  у меня равен nil. Это весьма странно в силу того, что в эту форму я попадаю из боковой панели

**Comment by arturdev** [comment]
Хмм.. Да уж, очень странно. 
Ну, так вслепую не могу сказать, должен посмотреть на код.

**Comment by ftp27** [comment]
Проблема была в невалидной инициализации класса самого. Не отправил аргументы родительскому классу и self.navigationController не назначился. Все ок теперь.

Спасибо за помощь!
