### ISSUE TITLE
Using custom Menu Button

### ISSUE THREAD

**Issue by ftp27** [SocialObjects-Software/AMSlideMenu#173]
How can I use third-party class buttons such as [VBFPopFlatButton](https://github.com/victorBaro/VBFPopFlatButton) for using it as Side Menu Button? If I implement the Button using methods of AMSlideMenuMainViewController, I can't change button image to normal state without delegate methods for detect closing and opening menu.

**Comment by arturdev** [comment]
You must override these methods in your MainVC class and change left bar button 
```ObjC
@optional
- (void)leftMenuWillOpen;
- (void)leftMenuDidOpen;
- (void)rightMenuWillOpen;
- (void)rightMenuDidOpen;

- (void)leftMenuWillClose;
- (void)leftMenuDidClose;
- (void)rightMenuWillClose;
- (void)rightMenuDidClose;
```

You can access to `UINavigationBar` instance by 
`self.currentActiveNVC.navigationBar`

**Comment by ftp27** [comment]
I did it! Thanks!

Last question: How can I open menu from View Controller? By creating MainVC as singleton?

**Comment by arturdev** [comment]
just import `"UIViewController+AMSlideMenu.h"` 
and call `[[self mainSlideMenu] openLeftMenuAnimated:YES];` whenever you want
