### ISSUE TITLE
Warning: Null passed to a callee that requires a non-null argument

### ISSUE THREAD

**Issue by riyanpratama** [SocialObjects-Software/AMSlideMenu#176]
Hi, my app runs but I get this warning
`/Users/riyanpratama/Documents/XCODE/myAMSlideMenu/myAMSlideMenu/AMSlideMenu/AMSlideMenuContentSegue.m:53:33: Null passed to a callee that requires a non-null argument`

It points to AMSlideMenuContentSegue class, on method -perform
`mainVC.currentActiveNVC.viewControllers = nil;`

I hope you aware of this warning and fix it asap. Thank you.

**Comment by arturdev** [comment]
Please, replace that line with following:
```
mainVC.currentActiveNVC.viewControllers = [NSArray new];
```
