### ISSUE TITLE
Pass data between content view when calling openContentViewControllerForMenu

### ISSUE THREAD

**Issue by Jasmond** [SocialObjects-Software/AMSlideMenu#179]
In one of my content view (1st view), I have a button to switch to another content view (2nd view), how do I pass data to the 2nd view when calling openContentViewControllerForMenu. Thanks a lot.

**Comment by arturdev** [comment]
Implement `- (void)prepareForSegue:sender:` method in your left/right table view controller. 
```ObjC
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    if ([segue.identifier isEqualToString:@"someContentSegue"])
    {
        MyViewController *vc = [segue.destinationViewController viewControllers][0];
        //pass data to vc
    }
}
```

**Comment by Jasmond** [comment]
Thanks for the prompt response. So I have to pass the data from 1st content view to the left menu table view controller first and then pass along to the 2nd view controller?

**Comment by arturdev** [comment]
Yes. 
And for the 2nd option you can pass your data through shared instances.

**Comment by Jasmond** [comment]
Got it thanks. Btw, I swipe right to reveal the left menu and I can tap on anywhere in the displayed content view to close the menu, how can I configure so that I swipe left to close the menu too?
