### ISSUE TITLE
Why change value of leftPanDisabled / rightPanDisabled in dealloc?

### ISSUE THREAD

**Issue by egold** [SocialObjects-Software/AMSlideMenu#96]
```
- (void)my_dealloc
{
    AMSlideMenuMainViewController *mainVC = [AMSlideMenuMainViewController getInstanceForVC:self];
    mainVC.leftPanDisabled = NO;
    mainVC.rightPanDisabled = NO;
    
    [self my_dealloc];
}
```

Any view controller that includes this category will now mess with the mainVC's pan behavior when the VC is deallocated. This seems really problematic, and indeed is causing a lot of problems for me. I want to disable the pan gestures while showing a tutorial or a details screen, but any VC anywhere that uses the category and gets deallocated is overriding this important property.

**Comment by cesar-cm** [comment]
same issue...
