### ISSUE TITLE
Introduction of a Modal View Controller breaks Left View Controller

### ISSUE THREAD

**Issue by domface** [SocialObjects-Software/AMSlideMenu#97]
Hi @arturdev 

Really love this library a ton! Arguably the best Slide Menu i've used to date.

I found something strange happening when i introduce a modal VC into my app from the Left View controller.

The Left View controller is "stuck" at the top of the view after i've implemented a modal vc and it's corresponding Segue. 

I also added an additional View to the top of my LVC so perhaps this has something to do with it too? I don't need a table view controller in this screen so therefore i've replaced it with a plain view.

Everything works after creating just the modal VC alone, however, when i add this line of code:

```Obj-C
-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    if ([segue.identifier isEqualToString:@"leftSegue"])
    {
    registerOrLoginModalVC *nextVC = [segue destinationViewController];
    [nextVC setModalDelegate:self];
    }
}
```

it causes this to happen when building the app:

![img_1486](https://cloud.githubusercontent.com/assets/1590035/3846697/f5789f4e-1e5e-11e4-8757-2aa4a5da45f0.png)

What i did as a work around was adding this line of code:

```Obj-C
-(void)viewDidAppear:(BOOL)animated
{
    [self closeLeftMenuAnimated:YES];
}
````

In my main VC. This loads up the VCs okay, however when i slide the left menu open, it blinks immediately to the picture i've shown above.

Now, if I use the closeLeftMenuAnimated method in my implementation and load up the App, it loads to my contentVC, however the LVC is visible for a split second before the content VC fully loads. 

![img_3270](https://cloud.githubusercontent.com/assets/1590035/3846829/3559b39a-1e60-11e4-96fb-bf7c148c27b5.PNG)

Now if i navigate from this content VC to the right VC, and select one of my options to change my current location:

![img_3271](https://cloud.githubusercontent.com/assets/1590035/3846868/88dbe740-1e60-11e4-9099-15a3ccd4c5ce.PNG)

The Left View Controller now slides properly,
![img_3272](https://cloud.githubusercontent.com/assets/1590035/3846869/9911b4f0-1e60-11e4-9b3e-d4d09bfdeb16.PNG)

And the modal from the left VC also works properly! Any ideas?

**Comment by arturdev** [comment]
Sorry for such a late answer.
The thing is that you shouldn't present your modal vc on the left or right menu, you must present it on the window's rootViewController, or on your mainVC instance.
